base_url = "https://ctron.github.io/trunk/"

title = "Trunk NG | Build, bundle & ship your Rust WASM application to the web"

compile_sass = true
highlight_code = true
highlight_theme = "inspired-github"
build_search_index = true
generate_feed = true

theme = "juice"

[extra]
favicon = "rustacean-flat-happy.svg"
juice_logo_name = "Trunk NG"
juice_logo_path = "rustacean-flat-happy.svg"
juice_extra_menu = [
    { title = "Github", link = "https://github.com/ctron/trunk"}
]
