name: Pages
on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup | Zola
        run: |
          wget -qO- https://github.com/getzola/zola/releases/download/v0.12.2/zola-v0.12.2-x86_64-unknown-linux-gnu.tar.gz | tar -xzf - \
          && sudo chmod a+x zola && sudo mv zola /bin/zola
      - name: Build
        run: cd site && zola build
      - name: Deploy
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./site/public
